name: Publish NuGet Package

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Contracts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./src/Contracts/Contracts.csproj
      
    - name: Build
      run: dotnet build ./src/Contracts/Contracts.csproj --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack ./src/Contracts/Contracts.csproj --configuration Release --no-build --output nupkgs
      
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
